"""All ORM models, imported so ``Base.metadata`` is complete for Alembic.

Scope classification (spec 03 §1):
- auth (no RLS): users, auth_sessions
- G (no RLS): source_templates, parser_versions
- O (RLS on app.owner_id): industries, industry_revisions, owner_feeds,
  source_runs, discovery_items, blobs, documents, document_origins,
  captures, fetch_observations, parsed_artifacts, document_diffs, chunks,
  processing_decisions, api_idempotency, index_generation (0003, INSERT-only
  retrieval-config registry)
- O/I hybrids (nullable industry_id, RLS on app.owner_id only — kind-level
  scoping, spec 03 §7): jobs, job_steps, job_events, model_runs,
  coverage_batches, audit_log
- I (RLS on app.owner_id + app.industry_id): topics, topic_revisions,
  industry_sources + every knowledge/conversation/generation table in
  RLS_INDUSTRY_TABLES below
"""

from intel.db.models.auth import AuthSession, User
from intel.db.models.conversation import (
    AuditLog,
    Conversation,
    ConversationStateRevision,
    ConversationSummaryRevision,
    DependencyEdge,
    DerivedStatus,
    Evolution,
    EvolutionCitation,
    EvolutionRevision,
    Message,
    MessageCitation,
    Report,
    ReportCitation,
    ReportRevision,
    ReviewTask,
)
from intel.db.models.generation import (
    GenerationRun,
    GenerationRunModel,
    OutputGeneration,
)
from intel.db.models.jobs import (
    ApiIdempotency,
    CoverageBatch,
    Job,
    JobEvent,
    JobStep,
    ModelRun,
    RecallHit,
)
from intel.db.models.knowledge import (
    Claim,
    ClaimRevision,
    ClaimRevisionEntity,
    DocumentAssociationHistory,
    DocumentTopic,
    Entity,
    EntityAlias,
    Event,
    EventAssociationHistory,
    EventLifecycleHistory,
    EventMergeOperation,
    EventReadState,
    EventRelation,
    EventRelationRevision,
    EventRevision,
    EventRevisionClaim,
    EventRevisionEntity,
    EventTopic,
    EventTopicRevision,
    EventTopicRevisionClaim,
    Evidence,
    IndustryDocument,
    RelationRevisionEvidence,
    SourceFamily,
    TopicRevisionEntity,
    Watch,
    WatchEntity,
    WatchTopic,
)
from intel.db.models.pool import (
    Blob,
    Capture,
    Chunk,
    DiscoveryItem,
    Document,
    DocumentDiff,
    DocumentOrigin,
    FetchObservation,
    ParsedArtifact,
    ProcessingDecision,
)
from intel.db.models.retrieval import IndexGeneration
from intel.db.models.sources import (
    IndustrySource,
    OwnerFeed,
    ParserVersion,
    SourceRun,
    SourceTemplate,
)
from intel.db.models.workspace import (
    Industry,
    IndustryRevision,
    Topic,
    TopicRevision,
)

AUTH_TABLES = ("users", "auth_sessions")
GLOBAL_TABLES = ("source_templates", "parser_versions")
RLS_OWNER_TABLES = (
    # 0001 O tables
    "industries",
    "industry_revisions",
    "owner_feeds",
    "source_runs",
    "discovery_items",
    "blobs",
    "documents",
    "document_origins",
    "captures",
    "fetch_observations",
    "parsed_artifacts",
    "document_diffs",
    "chunks",
    "processing_decisions",
    # 0002: O
    "api_idempotency",
    # 0002: O/I hybrids (nullable industry_id, owner-only RLS predicate)
    "jobs",
    "job_steps",
    "job_events",
    "model_runs",
    "coverage_batches",
    "audit_log",
    # 0003: retrieval index_generation registry (INSERT-only)
    "index_generation",
)
RLS_INDUSTRY_TABLES = (
    # 0001 I tables
    "topics",
    "topic_revisions",
    "industry_sources",
    # 0002: knowledge (spec 03 §4 + §9)
    "industry_documents",
    "document_topics",
    "entities",
    "entity_aliases",
    "claims",
    "claim_revisions",
    "evidence",
    "source_families",
    "events",
    "event_revisions",
    "event_topics",
    "event_topic_revisions",
    "event_relations",
    "event_relation_revisions",
    "watches",
    "overrides",
    "event_read_states",
    "topic_revision_entities",
    "claim_revision_entities",
    "event_revision_claims",
    "event_revision_entities",
    "event_topic_revision_claims",
    "relation_revision_evidence",
    "watch_topics",
    "watch_entities",
    "document_association_history",
    "event_association_history",
    "event_merge_operations",
    "event_lifecycle_history",
    # 0002: evolution/report/conversation (spec 03 §6, doc 16 §7)
    "evolutions",
    "evolution_revisions",
    "reports",
    "report_revisions",
    "conversations",
    "messages",
    "conversation_state_revisions",
    "conversation_summary_revisions",
    "review_tasks",
    "dependency_edges",
    "derived_status",
    "report_citations",
    "evolution_citations",
    "message_citations",
    # 0002: jobs I table (spec 03 §7)
    "recall_hits",
    # 0002: generation (doc 15 §3)
    "generation_runs",
    "generation_run_models",
    "output_generations",
)

ALL_TABLES = AUTH_TABLES + GLOBAL_TABLES + RLS_OWNER_TABLES + RLS_INDUSTRY_TABLES

__all__ = [
    "ALL_TABLES",
    "AUTH_TABLES",
    "GLOBAL_TABLES",
    "RLS_INDUSTRY_TABLES",
    "RLS_OWNER_TABLES",
    "ApiIdempotency",
    "AuditLog",
    "AuthSession",
    "Blob",
    "Capture",
    "Chunk",
    "Claim",
    "ClaimRevision",
    "ClaimRevisionEntity",
    "Conversation",
    "ConversationStateRevision",
    "ConversationSummaryRevision",
    "CoverageBatch",
    "DependencyEdge",
    "DerivedStatus",
    "DiscoveryItem",
    "Document",
    "DocumentAssociationHistory",
    "DocumentDiff",
    "DocumentOrigin",
    "DocumentTopic",
    "Entity",
    "EntityAlias",
    "Event",
    "EventAssociationHistory",
    "EventLifecycleHistory",
    "EventMergeOperation",
    "EventReadState",
    "EventRelation",
    "EventRelationRevision",
    "EventRevision",
    "EventRevisionClaim",
    "EventRevisionEntity",
    "EventTopic",
    "EventTopicRevision",
    "EventTopicRevisionClaim",
    "Evidence",
    "Evolution",
    "EvolutionCitation",
    "EvolutionRevision",
    "FetchObservation",
    "GenerationRun",
    "GenerationRunModel",
    "IndexGeneration",
    "Industry",
    "IndustryDocument",
    "IndustryRevision",
    "IndustrySource",
    "Job",
    "JobEvent",
    "JobStep",
    "Message",
    "MessageCitation",
    "ModelRun",
    "OutputGeneration",
    "OwnerFeed",
    "ParsedArtifact",
    "ParserVersion",
    "ProcessingDecision",
    "RecallHit",
    "RelationRevisionEvidence",
    "Report",
    "ReportCitation",
    "ReportRevision",
    "ReviewTask",
    "SourceFamily",
    "SourceRun",
    "SourceTemplate",
    "Topic",
    "TopicRevision",
    "TopicRevisionEntity",
    "User",
    "Watch",
    "WatchEntity",
    "WatchTopic",
]
